name: dreambooth
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - cudatoolkit=11.6
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - torch==1.12.1+cu116
    - torchaudio==0.12.1
    - torchvision==0.13.1+cu116
    - diffusers
    - transformers
    - accelerate
    - triton
    - ftfy
    - tensorboard
    - Jinja2
    - gpustat